services:
  app-database:
    container_name: app-database
    platform: linux/arm64
    image: postgres:17
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_database
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data

  dashboard:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "18081:80"
    depends_on:
      - app-database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
volumes:
  pg_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge